### ISSUE TITLE
class java.io.IOException Operation timed out

### ISSUE THREAD

**Issue by heychirag** [spotware/ctrader-open-api-v2-java-example#10]
**Describe the bug**
The listener timed out after it didn't receive any messages for a while.

**To Reproduce**
Create a listener using `nettyClient.addListener()` and let it stay open. It will time out after a few hours if no message is received.

**Expected behavior**
The connection should stay alive always.

**Log files**

```
2020-08-13 18:09:55 WARN  CloseOnExceptionHandler:66 - Exception caught in channel [id: 0x6c81328b, L:/10.0.10.34:55726 - R:live.ctraderapi.com/185.17.146.199:5035]: class java.io.IOException Operation timed out. Closing channel.
```

**Additional context**

**Comment by LeoSko** [comment]
I'll try to reproduce it, but I wonder if there were any authentication in the connection, any requests at all? Would be nice to see log from the start of connection (you can cut out any sensitive data if you wish).

**Comment by heychirag** [comment]
I ran the second time and it hasn't happened for many hours now. Hope it keeps running like this. But there could be some reliability issues. My program runs the following set of commands essentially:

```
NettyClient nettyClient = new NettyClient(<Host>, <Port>);

AuthHelper authHelper = nettyClient.getAuthHelper();

authHelper.authorizeApplication(<Client ID>, <Client Secret>);

authHelper.authorizeAccount(<Account ID>, <Access Token>);

nettyClient.addListener();
```

**Comment by LeoSko** [comment]
My client worked today for hours with no issues. Reopen if reproduced and don't forget to attach some logs.

**Comment by heychirag** [comment]
I got this again right now. This is dangerous and can cost me a lot.
