### ISSUE TITLE
class java.io.IOException Operation timed out - 2

### ISSUE THREAD

**Issue by heychirag** [spotware/ctrader-open-api-v2-java-example#12]
I just faced this issue again. It's very ad-hoc and looks like can happen anytime.

Sorry I don't have permissions to reopen the previous issue.

**Comment by LeoSko** [comment]
Can I ask you **not to forget logs** please? We need at least some specific info to investigate.

**Comment by heychirag** [comment]
```
2020-08-13 18:09:55 WARN  CloseOnExceptionHandler:66 - Exception caught in channel [id: 0x6c81328b, L:/10.0.10.34:55726 - R:live.ctraderapi.com/185.17.146.199:5035]: class java.io.IOException Operation timed out. Closing channel.

```

This is the only error it throws. I have enabled the debug error as well now. Will see what it sends the next time it happens.

**Comment by LeoSko** [comment]
Those are the logs that you attached to the original issue and they are useless for me. Also note that it would be nice to have a timezone in logs.
