### ISSUE TITLE
Any plans to create SDK in Golang or Javascript?

### ISSUE THREAD

**Issue by GoChartingAdmin** [spotware/ctrader-open-api-v2-java-example#15]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amusleh-spotware-com** [comment]
Hi,
Right now we don't have any plan to create SDK for JS or Go but we have one for .NET: https://github.com/spotware/OpenAPI.Net
And we will create another one for Python in future.
