### ISSUE TITLE
Getting historical trades

### ISSUE THREAD

**Issue by ampbj** [spotware/ctrader-open-api-v2-java-example#16]
Hi,

I am using "ProtoOADealListReq" to get historical trades of my demo account.
No matter what unix time value I use for "fromTimestamp" and "toTimestamp". I get no deals even though during that time I had trades executed. I also used "ProtoOACashFlowHistoryListReq" but no results either.
Can you please help?

**Comment by LeoSko** [comment]
@ampbj, hi. This is openapi java example repository, you need to report this to our forum instead: https://ctrader.com/forum/connect-api-support
Please include full log of your requests and responses with timestamps and timezone.
