### ISSUE TITLE
Cannot build com.xtrader.protocol.openapi.v2.*

### ISSUE THREAD

**Issue by puguri** [spotware/ctrader-open-api-v2-java-example#9]
**Describe the bug**
Package does not exist.
Error:(15, 42) java: package com.xtrader.protocol.proto.commons does not exist

**Log files**
Information:java: Errors occurred while compiling module 'openapi2-client'
Information:javac 1.8.0_144 was used to compile java sources
Information:Modules "openapi2-client", "openapi2-example" were fully rebuilt due to project configuration/dependencies changes
Information:7/16/20, 16:02 - Build completed with 100 errors and 0 warnings in 6 s 280 ms
/Users/hienphung/IdeaProjects/ctrader-open-api-v2-java-example/openapi2-client/src/main/java/com/spotware/connect/protocol/ProtoMessageFactory.java
    Error:Error:line (15)java: package com.xtrader.protocol.proto.commons does not exist
    Error:Error:line (59)java: cannot find symbol
  symbol:   class ProtoMessage
  location: class com.spotware.connect.protocol.ProtoMessageFactory
    Error:Error:line (72)java: cannot find symbol
  symbol:   class ProtoMessage
  location: class com.spotware.connect.protocol.ProtoMessageFactory
    Error:Error:line (60)java: package ProtoMessage does not exist
    Error:Error:line (60)java: cannot find symbol
  symbol:   variable ProtoMessage
  location: class com.spotware.connect.protocol.ProtoMessageFactory
/Users/hienphung/IdeaProjects/ctrader-open-api-v2-java-example/openapi2-client/src/main/java/com/spotware/connect/protocol/OA2ProtoMessageFactory.java
    Error:Error:line (5)java: package com.xtrader.protocol.openapi.v2 does not exist
    Error:Error:line (6)java: package com.xtrader.protocol.openapi.v2 does not exist
    Error:Error:line (7)java: package com.xtrader.protocol.openapi.v2 does not exist
    Error:Error:line (8)java: package com.xtrader.protocol.openapi.v2 does not exist
    Error:Error:line (9)java: package com.xtrader.protocol.openapi.v2 does not exist
    Error:Error:line (10)java: package com.xtrader.protocol.openapi.v2 does not exist
    Error:Error:line (11)java: package com.xtrader.protocol.openapi.v2 does not exist
.....

**Comment by LeoSko** [comment]
What command did you use?
